#!/usr/bin/env bash
# render-db-mongoose.sh — R6 DB renderer (Mongoose)
# Triggered when dataArchitecture.engine = mongodb. Sources render-common.sh.
# Emits a JSON envelope { content, sourceRefs, crossCheckWarnings } to stdout.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=render-common.sh
source "${SCRIPT_DIR}/render-common.sh"

STATE_FILE="${1:?usage: render-db-mongoose.sh <state-file>}"
ENTITIES=$(_validate_jq_path "$STATE_FILE" '.phases.domainModel.entities // []' false)
PII=$(_validate_jq_path "$STATE_FILE" '.phases.privacy.piiFields // []' false)

HEADER='// Generated by greenfield render-db-mongoose.sh — review and edit freely after lock.
import mongoose, { Schema, Document } from "mongoose";
'

MODELS=""
SRC_REFS="[]"
WARNINGS="[]"

ENTITY_COUNT=$(jq 'length' <<< "$ENTITIES")
for i in $(seq 0 $((ENTITY_COUNT - 1))); do
  E=$(jq ".[$i]" <<< "$ENTITIES")
  NAME=$(jq -r '.name // .id // "Unknown"' <<< "$E")

  ATTRS=$(jq '.attributes // []' <<< "$E")
  A_COUNT=$(jq 'length' <<< "$ATTRS")
  FIELDS_BLOCK=""
  for j in $(seq 0 $((A_COUNT - 1))); do
    AN=$(jq -r ".[$j].name // \"f${j}\"" <<< "$ATTRS")
    AT=$(jq -r ".[$j].type // \"String\"" <<< "$ATTRS")
    case "$AT" in
      string|String|text)     MT="String" ;;
      int|integer|Int)        MT="Number" ;;
      bool|boolean|Boolean)   MT="Boolean" ;;
      date|datetime|DateTime) MT="Date" ;;
      float|number|Float)     MT="Number" ;;
      *)                      MT="String" ;;
    esac
    FIELDS_BLOCK="${FIELDS_BLOCK}
  ${AN}: { type: ${MT} },"
    WARNINGS=$(_check_pii_encryption "${NAME}.${AN}" "$PII" "$WARNINGS")
  done

  MODELS="${MODELS}
interface I${NAME} extends Document {}
const ${NAME}Schema = new Schema<I${NAME}>({${FIELDS_BLOCK}
}, { timestamps: true });
export const ${NAME} = mongoose.model<I${NAME}>('${NAME}', ${NAME}Schema);
"
  SRC_REFS=$(jq --arg n "$NAME" '. + [{path: ("domainModel.entities[name=" + $n + "]"), renderedAs: ("Mongoose model " + $n)}]' <<< "$SRC_REFS")
done

CONTENT="${HEADER}${MODELS}"
jq -n --arg content "$CONTENT" --argjson srcRefs "$SRC_REFS" --argjson warnings "$WARNINGS" \
  '{content: $content, sourceRefs: $srcRefs, crossCheckWarnings: $warnings}'
