#!/usr/bin/env bash
# render-api-graphql.sh — R5 P10.5 API renderer (GraphQL SDL)
#
# Reads apiIntegration + auth + domainModel + privacy from $1, emits a
# GraphQL SDL string wrapped in a JSON envelope to stdout.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=render-common.sh
source "${SCRIPT_DIR}/render-common.sh"

STATE_FILE="${1:?usage: render-api-graphql.sh <state-file>}"

ENDPOINTS=$(jq '.phases.apiIntegration.endpoints // []' "$STATE_FILE")
SCOPES_JSON=$(jq '.phases.auth.scopes // []' "$STATE_FILE")
ENTITIES=$(jq '.phases.domainModel.entities // []' "$STATE_FILE")
PII=$(jq '.phases.privacy.piiFields // []' "$STATE_FILE")

HEADER='# Generated by greenfield render-api-graphql.sh — review and edit freely after lock.'

SRC_REFS="[]"
WARNINGS="[]"
USED_SCOPES_FILE=$(mktemp)

# --- Attribute type mapping ---------------------------------------------------
map_gql_type() {
  local raw
  raw=$(echo "${1:-}" | tr '[:upper:]' '[:lower:]')
  case "$raw" in
    string|text)        echo "String" ;;
    int|integer)        echo "Int" ;;
    bool|boolean)       echo "Boolean" ;;
    date|datetime)      echo "String" ;;
    float|number)       echo "Float" ;;
    *)                  echo "String" ;;
  esac
}

# --- Helpers for naming -------------------------------------------------------
# Lowercase the first char of a name (for query field names).
lcfirst() {
  local s="${1:-}"
  if [[ -z "$s" ]]; then
    echo ""
    return
  fi
  local first rest
  first=$(printf '%s' "${s:0:1}" | tr '[:upper:]' '[:lower:]')
  rest="${s:1}"
  printf '%s%s' "$first" "$rest"
}

# Naive pluralizer for collection field names. Good enough for sensible SDL.
pluralize() {
  local s="${1:-}"
  local last2 last1
  last2="${s: -2}"
  last1="${s: -1}"
  if [[ "$last1" == "y" && ! "$last2" =~ [aeiouAEIOU]y$ ]]; then
    printf '%sies' "${s%?}"
  elif [[ "$last1" == "s" || "$last1" == "x" || "$last2" == "ch" || "$last2" == "sh" ]]; then
    printf '%ses' "$s"
  else
    printf '%ss' "$s"
  fi
}

# --- Entity type emission -----------------------------------------------------
TYPES_STR=""
ENT_COUNT=$(jq 'length' <<< "$ENTITIES")
for k in $(seq 0 $((ENT_COUNT - 1))); do
  ENT=$(jq ".[$k]" <<< "$ENTITIES")
  EN=$(jq -r '(.name // .id)' <<< "$ENT")
  [[ -z "$EN" || "$EN" == "null" ]] && continue

  TYPES_STR="${TYPES_STR}
type ${EN} {
  id: ID!"

  ATTR_COUNT=$(jq '(.attributes // []) | length' <<< "$ENT")
  for a in $(seq 0 $((ATTR_COUNT - 1))); do
    ATTR=$(jq ".attributes[$a]" <<< "$ENT")
    AN=$(jq -r '.name // ""' <<< "$ATTR")
    AT=$(jq -r '.type // "string"' <<< "$ATTR")
    [[ -z "$AN" || "$AN" == "null" ]] && continue
    GQL_TYPE=$(map_gql_type "$AT")
    TYPES_STR="${TYPES_STR}
  ${AN}: ${GQL_TYPE}"
  done

  TYPES_STR="${TYPES_STR}
}
"

  SRC_REFS=$(jq --arg p "phases.domainModel.entities[${k}]" --arg r "type ${EN}" \
    '. + [{path: $p, renderedAs: $r}]' <<< "$SRC_REFS")
done

# --- Endpoint emission (Query + Mutation) -------------------------------------
QUERY_FIELDS=""
MUTATION_FIELDS=""

EC=$(jq 'length' <<< "$ENDPOINTS")
for i in $(seq 0 $((EC - 1))); do
  EP=$(jq ".[$i]" <<< "$ENDPOINTS")
  METHOD=$(jq -r '.method // "GET" | ascii_upcase' <<< "$EP")
  PATH_VAL=$(jq -r '.path // "/"' <<< "$EP")
  ENTITY=$(jq -r '.entity // ""' <<< "$EP")
  SCOPE=$(jq -r '.scope // ""' <<< "$EP")
  [[ -n "$SCOPE" ]] && echo "$SCOPE" >> "$USED_SCOPES_FILE"

  # Strip trailing slash for analysis.
  CLEAN_PATH="${PATH_VAL%/}"
  [[ -z "$CLEAN_PATH" ]] && CLEAN_PATH="/"

  # Detect if path has an id segment ({id} or :id at the end).
  HAS_ID=0
  case "$CLEAN_PATH" in
    */\{*\}|*/:*) HAS_ID=1 ;;
  esac

  # Derive a default entity name from the path's collection segment if not provided.
  if [[ -z "$ENTITY" || "$ENTITY" == "null" ]]; then
    # Take the segment immediately before an id placeholder, or the trailing segment.
    if [[ "$HAS_ID" == "1" ]]; then
      COLL_SEG="${CLEAN_PATH%/*}"
      COLL_SEG="${COLL_SEG##*/}"
    else
      COLL_SEG="${CLEAN_PATH##*/}"
    fi
    # Title-case + singularize (very naive: trim trailing 's').
    case "$COLL_SEG" in
      *s) COLL_SEG="${COLL_SEG%s}" ;;
    esac
    if [[ -n "$COLL_SEG" ]]; then
      ENTITY="$(echo "${COLL_SEG:0:1}" | tr '[:lower:]' '[:upper:]')${COLL_SEG:1}"
    else
      ENTITY="Item"
    fi
  fi

  ENTITY_LC=$(lcfirst "$ENTITY")
  ENTITY_PL=$(pluralize "$ENTITY_LC")

  case "$METHOD" in
    GET)
      if [[ "$HAS_ID" == "1" ]]; then
        QUERY_FIELDS="${QUERY_FIELDS}
  ${ENTITY_LC}(id: ID!): ${ENTITY}"
      else
        QUERY_FIELDS="${QUERY_FIELDS}
  ${ENTITY_PL}: [${ENTITY}!]!"
      fi
      RENDERED="Query.${ENTITY_LC}"
      ;;
    POST)
      MUTATION_FIELDS="${MUTATION_FIELDS}
  create${ENTITY}: ${ENTITY}"
      RENDERED="Mutation.create${ENTITY}"
      ;;
    PUT|PATCH)
      MUTATION_FIELDS="${MUTATION_FIELDS}
  update${ENTITY}(id: ID!): ${ENTITY}"
      RENDERED="Mutation.update${ENTITY}"
      ;;
    DELETE)
      MUTATION_FIELDS="${MUTATION_FIELDS}
  delete${ENTITY}(id: ID!): Boolean"
      RENDERED="Mutation.delete${ENTITY}"
      ;;
    *)
      RENDERED="${METHOD} ${PATH_VAL}"
      ;;
  esac

  SRC_REFS=$(jq --arg p "phases.apiIntegration.endpoints[${i}]" --arg r "$RENDERED" \
    '. + [{path: $p, renderedAs: $r}]' <<< "$SRC_REFS")

  # Warning: endpoint touches entity with PII fields and no redaction note.
  if [[ -n "$ENTITY" ]]; then
    PII_FIELDS_IN_ENTITY=$(jq --arg e "$ENTITY" '[.[] | select(.path | startswith($e + "."))] | length' <<< "$PII")
    if [[ "$PII_FIELDS_IN_ENTITY" -gt 0 ]]; then
      WARN_ID="W-API-${i}-pii"
      MSG="Endpoint \`${METHOD} ${PATH_VAL}\` exposes PII fields from \`${ENTITY}\` in response without redaction note"
      WARNINGS=$(_emit_warning "error" "$WARN_ID" "$MSG" "$WARNINGS")
    fi
  fi
done

# --- Warning: auth scope unused ----------------------------------------------
SCOPE_COUNT=$(jq 'length' <<< "$SCOPES_JSON")
for k in $(seq 0 $((SCOPE_COUNT - 1))); do
  SN=$(jq -r ".[$k] | (.name // .)" <<< "$SCOPES_JSON")
  [[ -z "$SN" || "$SN" == "null" ]] && continue
  if ! grep -qxF "$SN" "$USED_SCOPES_FILE" 2>/dev/null; then
    WARN_ID="W-API-scope-${k}"
    MSG="Auth scope \`${SN}\` is not used by any endpoint"
    WARNINGS=$(_emit_warning "warn" "$WARN_ID" "$MSG" "$WARNINGS")
  fi
done

# --- Warning: entity has no endpoint -----------------------------------------
for k in $(seq 0 $((ENT_COUNT - 1))); do
  EN=$(jq -r ".[$k] | (.name // .id)" <<< "$ENTITIES")
  [[ -z "$EN" || "$EN" == "null" ]] && continue
  HAS_EP=$(jq --arg n "$EN" '[.[] | select(.entity == $n)] | length' <<< "$ENDPOINTS")
  if [[ "$HAS_EP" == "0" ]]; then
    WARN_ID="W-API-noep-${k}"
    MSG="Entity \`${EN}\` has no API endpoint — intentional?"
    WARNINGS=$(_emit_warning "warn" "$WARN_ID" "$MSG" "$WARNINGS")
  fi
done

rm -f "$USED_SCOPES_FILE"

# --- Assemble SDL -------------------------------------------------------------
# Always emit Query and Mutation blocks for predictability; if no fields, emit a
# placeholder `_empty: Boolean` so the SDL remains valid.
[[ -z "$QUERY_FIELDS" ]] && QUERY_FIELDS="
  _empty: Boolean"
[[ -z "$MUTATION_FIELDS" ]] && MUTATION_FIELDS="
  _empty: Boolean"

CONTENT="${HEADER}
${TYPES_STR}
type Query {${QUERY_FIELDS}
}

type Mutation {${MUTATION_FIELDS}
}
"

jq -n --arg content "$CONTENT" --argjson srcRefs "$SRC_REFS" --argjson warnings "$WARNINGS" \
  '{content: $content, sourceRefs: $srcRefs, crossCheckWarnings: $warnings}'
