#!/usr/bin/env bash
# render-event-asyncapi.sh — R5 P10.5 Event renderer (AsyncAPI 2.6)
#
# Reads phases.domainModel.domainEvents[] + phases.runtimeOperations.observability
# and emits an AsyncAPI 2.6 YAML doc with one channel per domain event.

set -euo pipefail
STATE_FILE="${1:?usage: render-event-asyncapi.sh <state-file>}"

EVENTS=$(jq '.phases.domainModel.domainEvents // []' "$STATE_FILE")

HEADER='asyncapi: 2.6.0
info:
  title: Domain Events
  version: 0.1.0
  description: Generated by greenfield render-event-asyncapi.sh — review and edit freely after lock.
channels:'

CHANNELS=""
SRC_REFS="[]"
WARNINGS="[]"

EV_COUNT=$(jq 'length' <<< "$EVENTS")
for i in $(seq 0 $((EV_COUNT - 1))); do
  EV=$(jq ".[$i]" <<< "$EVENTS")
  EV_NAME=$(jq -r '.name // .id // empty' <<< "$EV")
  [[ -z "$EV_NAME" || "$EV_NAME" == "null" ]] && EV_NAME="event$i"
  HAS_PAYLOAD=$(jq -r '.payload | type' <<< "$EV" 2>/dev/null || echo "null")
  CONSUMER_COUNT=$(jq -r '(.consumers // []) | length' <<< "$EV" 2>/dev/null || echo "0")

  # Render channel
  CHANNELS="${CHANNELS}
  ${EV_NAME}:
    subscribe:
      message:
        name: ${EV_NAME}
        payload:
          type: object"
  if [[ "$HAS_PAYLOAD" == "object" ]]; then
    PROPS_BLOCK=$(jq -r '.payload | to_entries | map("            " + .key + ": { type: " + (if (.value | type) == "string" then .value else "string" end) + " }") | join("\n")' <<< "$EV")
    if [[ -n "$PROPS_BLOCK" ]]; then
      CHANNELS="${CHANNELS}
          properties:
${PROPS_BLOCK}"
    fi
  fi

  SRC_REFS=$(jq --arg p "phases.domainModel.domainEvents[${i}]" --arg r "channel ${EV_NAME}" '. + [{path: $p, renderedAs: $r}]' <<< "$SRC_REFS")

  if [[ "$HAS_PAYLOAD" != "object" ]]; then
    WARN_ID="W-EV-${i}-nopayload"
    MSG="Event \`${EV_NAME}\` has no payload schema in domainModel"
    WARNINGS=$(jq --arg id "$WARN_ID" --arg msg "$MSG" '. + [{id: $id, level: "warn", message: $msg}]' <<< "$WARNINGS")
  fi

  if [[ "$CONSUMER_COUNT" -eq 0 ]]; then
    WARN_ID="W-EV-${i}-noconsumer"
    MSG="Domain event \`${EV_NAME}\` has no consumer registered"
    WARNINGS=$(jq --arg id "$WARN_ID" --arg msg "$MSG" '. + [{id: $id, level: "info", message: $msg}]' <<< "$WARNINGS")
  fi
done

CONTENT="${HEADER}${CHANNELS}
"

jq -n --arg content "$CONTENT" --argjson srcRefs "$SRC_REFS" --argjson warnings "$WARNINGS" \
  '{content: $content, sourceRefs: $srcRefs, crossCheckWarnings: $warnings}'
