#!/usr/bin/env bash
# render-db-sql-ddl.sh — R5 P10.5 DB renderer (SQL DDL)
#
# Reads domain model + privacy from $1 and emits SQL DDL (PostgreSQL flavor)
# wrapped in a JSON envelope to stdout. sourceRefs map each rendered table
# back to its origin entity. crossCheckWarnings surface aggregate-roots-without-PK
# and PII-without-encryption-hint.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=render-common.sh
source "${SCRIPT_DIR}/render-common.sh"

STATE_FILE="${1:?usage: render-db-sql-ddl.sh <state-file>}"

ENTITIES=$(jq '.phases.domainModel.entities // []' "$STATE_FILE")
PII=$(jq '.phases.privacy.piiFields // []' "$STATE_FILE")

HEADER='-- Generated by greenfield render-db-sql-ddl.sh — review and edit freely after lock.
'

# Convert CamelCase / PascalCase / camelCase to snake_case.
# Examples: AuditLog → audit_log, userAccount → user_account, Audit → audit.
to_snake_case() {
  local in="$1"
  # Insert underscore between lowercase/digit and uppercase, then lowercase all.
  printf '%s' "$in" \
    | sed -E 's/([a-z0-9])([A-Z])/\1_\2/g' \
    | tr '[:upper:]' '[:lower:]'
}

TABLES=""
SRC_REFS="[]"
WARNINGS="[]"

ENTITY_COUNT=$(jq 'length' <<< "$ENTITIES")
for i in $(seq 0 $((ENTITY_COUNT - 1))); do
  E=$(jq ".[$i]" <<< "$ENTITIES")
  NAME=$(jq -r '.name // .id // "Unknown"' <<< "$E")
  TABLE_NAME=$(to_snake_case "$NAME")
  IS_AGGREGATE_ROOT=$(jq -r '.isAggregateRoot // false' <<< "$E")
  PK_FIELD=$(jq -r '.primaryKey // ""' <<< "$E")

  if [[ "$IS_AGGREGATE_ROOT" == "true" && -z "$PK_FIELD" ]]; then
    WARN_ID="W-DB-${i}-pk"
    MSG="Aggregate root \`${NAME}\` has no PK field — cannot generate schema"
    WARNINGS=$(_emit_warning "error" "$WARN_ID" "$MSG" "$WARNINGS")
    PK_FIELD="id"
  fi
  [[ -z "$PK_FIELD" ]] && PK_FIELD="id"

  FIELDS_BLOCK="  ${PK_FIELD} SERIAL PRIMARY KEY"

  ATTRS=$(jq '.attributes // []' <<< "$E")
  A_COUNT=$(jq 'length' <<< "$ATTRS")
  for j in $(seq 0 $((A_COUNT - 1))); do
    AN=$(jq -r ".[$j].name // \"f${j}\"" <<< "$ATTRS")
    AT=$(jq -r ".[$j].type // \"string\"" <<< "$ATTRS")
    case "$AT" in
      string|String|text)        ST="VARCHAR(255)" ;;
      int|integer|Int)           ST="INTEGER" ;;
      bool|boolean|Boolean)      ST="BOOLEAN" ;;
      date|datetime|DateTime)    ST="TIMESTAMP" ;;
      float|number|Float)        ST="DOUBLE PRECISION" ;;
      *)                         ST="VARCHAR(255)" ;;
    esac
    [[ "$AN" == "$PK_FIELD" ]] && continue
    FIELDS_BLOCK="${FIELDS_BLOCK},
  ${AN} ${ST}"

    WARNINGS=$(_check_pii_encryption "${NAME}.${AN}" "$PII" "$WARNINGS")
  done

  TABLES="${TABLES}
CREATE TABLE \"${TABLE_NAME}\" (
${FIELDS_BLOCK},
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"

  SRC_REFS=$(jq --arg p "phases.domainModel.entities[${i}]" --arg r "CREATE TABLE \"${TABLE_NAME}\"" '. + [{path: $p, renderedAs: $r}]' <<< "$SRC_REFS")
done

CONTENT="${HEADER}${TABLES}"

jq -n --arg content "$CONTENT" --argjson srcRefs "$SRC_REFS" --argjson warnings "$WARNINGS" \
  '{content: $content, sourceRefs: $srcRefs, crossCheckWarnings: $warnings}'
