#!/usr/bin/env bash
# render-api-trpc.sh — R6 API renderer (tRPC router types)
# Triggered when apiIntegration.style = trpc.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=render-common.sh
source "${SCRIPT_DIR}/render-common.sh"

STATE_FILE="${1:?usage: render-api-trpc.sh <state-file>}"
ENDPOINTS=$(_validate_jq_path "$STATE_FILE" '.phases.apiIntegration.endpoints // []' false)

HEADER='// Generated by greenfield render-api-trpc.sh — review and edit freely after lock.
import { z } from "zod";
import { router, publicProcedure } from "./trpc";

export const appRouter = router({'

PROCS=""
SRC_REFS="[]"
WARNINGS="[]"

E_COUNT=$(jq 'length' <<< "$ENDPOINTS")
for i in $(seq 0 $((E_COUNT - 1))); do
  EP=$(jq ".[$i]" <<< "$ENDPOINTS")
  NAME=$(jq -r '.name // .id // ("op" + (.path // "" | gsub("/"; "_")))' <<< "$EP")
  TYPE=$(jq -r '.type // "query"' <<< "$EP")
  KIND=$([[ "$TYPE" == "mutation" ]] && echo "mutation" || echo "query")

  PROCS="${PROCS}
  ${NAME}: publicProcedure.input(z.object({})).${KIND}(({ input }) => {
    // implement
    return {};
  }),"
  SRC_REFS=$(jq --arg n "$NAME" '. + [{path: ("apiIntegration.endpoints[name=" + $n + "]"), renderedAs: ("tRPC " + "'"$KIND"'" + " " + $n)}]' <<< "$SRC_REFS")
done

[[ "$E_COUNT" -eq 0 ]] && WARNINGS=$(_emit_warning "info" "I-TRPC-empty" "No apiIntegration.endpoints[] — emitting empty router" "$WARNINGS")

CONTENT="${HEADER}${PROCS}
});

export type AppRouter = typeof appRouter;"

jq -n --arg content "$CONTENT" --argjson srcRefs "$SRC_REFS" --argjson warnings "$WARNINGS" \
  '{content: $content, sourceRefs: $srcRefs, crossCheckWarnings: $warnings}'
