#!/usr/bin/env bash
# render-event-json-schema.sh — R5 P10.5 Event renderer (JSON Schema)
#
# Reads phases.domainModel.domainEvents[] and emits a single JSON Schema doc
# with one event schema per entry keyed by event name. Mirrors the warning
# categories of render-event-asyncapi.sh.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=render-common.sh
source "${SCRIPT_DIR}/render-common.sh"

STATE_FILE="${1:?usage: render-event-json-schema.sh <state-file>}"

EVENTS=$(jq '.phases.domainModel.domainEvents // []' "$STATE_FILE")

EVENTS_OBJ='{}'
SRC_REFS="[]"
WARNINGS="[]"

EV_COUNT=$(jq 'length' <<< "$EVENTS")
for i in $(seq 0 $((EV_COUNT - 1))); do
  EV=$(jq ".[$i]" <<< "$EVENTS")
  EV_NAME=$(jq -r '.name // .id // empty' <<< "$EV")
  [[ -z "$EV_NAME" || "$EV_NAME" == "null" ]] && EV_NAME="event${i}"
  HAS_PAYLOAD=$(jq -r '.payload | type' <<< "$EV" 2>/dev/null || echo "null")
  CONSUMER_COUNT=$(jq -r '(.consumers // []) | length' <<< "$EV" 2>/dev/null || echo "0")

  if [[ "$HAS_PAYLOAD" == "object" ]]; then
    PROPS=$(jq '.payload | to_entries | map({(.key): {type: (if (.value | type) == "string" then .value else "string" end)}}) | add // {}' <<< "$EV")
  else
    PROPS='{}'
  fi

  EVENTS_OBJ=$(jq --arg n "$EV_NAME" --argjson props "$PROPS" '. + {($n): {"type": "object", "properties": $props}}' <<< "$EVENTS_OBJ")

  SRC_REFS=$(jq --arg p "phases.domainModel.domainEvents[${i}]" --arg r "event ${EV_NAME}" '. + [{path: $p, renderedAs: $r}]' <<< "$SRC_REFS")

  if [[ "$HAS_PAYLOAD" != "object" ]]; then
    WARN_ID="W-EV-${i}-nopayload"
    MSG="Event \`${EV_NAME}\` has no payload schema in domainModel"
    WARNINGS=$(_emit_warning "warn" "$WARN_ID" "$MSG" "$WARNINGS")
  fi

  if [[ "$CONSUMER_COUNT" -eq 0 ]]; then
    WARN_ID="W-EV-${i}-noconsumer"
    MSG="Domain event \`${EV_NAME}\` has no consumer registered"
    WARNINGS=$(_emit_warning "info" "$WARN_ID" "$MSG" "$WARNINGS")
  fi
done

CONTENT=$(jq -n --argjson events "$EVENTS_OBJ" '{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$comment": "Generated by greenfield render-event-json-schema.sh — review and edit freely after lock.",
  "events": $events
}')

jq -n --arg content "$CONTENT" --argjson srcRefs "$SRC_REFS" --argjson warnings "$WARNINGS" \
  '{content: $content, sourceRefs: $srcRefs, crossCheckWarnings: $warnings}'
