#!/usr/bin/env bash
# render-api-openapi.sh — R5 P10.5 API renderer (OpenAPI 3.0)
#
# Reads apiIntegration + auth + domainModel + privacy from $1, emits an
# OpenAPI 3.0 YAML string wrapped in a JSON envelope to stdout.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=render-common.sh
source "${SCRIPT_DIR}/render-common.sh"

STATE_FILE="${1:?usage: render-api-openapi.sh <state-file>}"

ENDPOINTS=$(jq '.phases.apiIntegration.endpoints // []' "$STATE_FILE")
SCOPES_JSON=$(jq '.phases.auth.scopes // []' "$STATE_FILE")
ENTITIES=$(jq '.phases.domainModel.entities // []' "$STATE_FILE")
PII=$(jq '.phases.privacy.piiFields // []' "$STATE_FILE")

HEADER='openapi: 3.0.0
info:
  title: API
  version: 0.1.0
  description: Generated by greenfield render-api-openapi.sh — review and edit freely after lock.
paths:'

PATHS_STR=""
SRC_REFS="[]"
WARNINGS="[]"
USED_SCOPES_FILE=$(mktemp)

EC=$(jq 'length' <<< "$ENDPOINTS")
for i in $(seq 0 $((EC - 1))); do
  EP=$(jq ".[$i]" <<< "$ENDPOINTS")
  METHOD=$(jq -r '.method // "GET" | ascii_downcase' <<< "$EP")
  METHOD_UPPER=$(echo "$METHOD" | tr '[:lower:]' '[:upper:]')
  PATH_VAL=$(jq -r '.path // "/"' <<< "$EP")
  ENTITY=$(jq -r '.entity // ""' <<< "$EP")
  SCOPE=$(jq -r '.scope // ""' <<< "$EP")
  [[ -n "$SCOPE" ]] && echo "$SCOPE" >> "$USED_SCOPES_FILE"

  PATHS_STR="${PATHS_STR}
  ${PATH_VAL}:
    ${METHOD}:
      summary: ${METHOD_UPPER} ${PATH_VAL}
      responses:
        '200':
          description: Success"
  if [[ -n "$SCOPE" ]]; then
    PATHS_STR="${PATHS_STR}
      security:
        - bearerAuth: [${SCOPE}]"
  fi

  SRC_REFS=$(jq --arg p "phases.apiIntegration.endpoints[${i}]" --arg r "${METHOD_UPPER} ${PATH_VAL}" '. + [{path: $p, renderedAs: $r}]' <<< "$SRC_REFS")

  if [[ -n "$ENTITY" ]]; then
    PII_FIELDS_IN_ENTITY=$(jq --arg e "$ENTITY" '[.[] | select(.path | startswith($e + "."))] | length' <<< "$PII")
    if [[ "$PII_FIELDS_IN_ENTITY" -gt 0 ]]; then
      WARN_ID="W-API-${i}-pii"
      MSG="Endpoint \`${METHOD_UPPER} ${PATH_VAL}\` exposes PII fields from \`${ENTITY}\` in response without redaction note"
      WARNINGS=$(_emit_warning "error" "$WARN_ID" "$MSG" "$WARNINGS")
    fi
  fi
done

SCOPE_COUNT=$(jq 'length' <<< "$SCOPES_JSON")
for k in $(seq 0 $((SCOPE_COUNT - 1))); do
  SN=$(jq -r ".[$k] | (.name // .)" <<< "$SCOPES_JSON")
  [[ -z "$SN" || "$SN" == "null" ]] && continue
  if ! grep -qxF "$SN" "$USED_SCOPES_FILE" 2>/dev/null; then
    WARN_ID="W-API-scope-${k}"
    MSG="Auth scope \`${SN}\` is not used by any endpoint"
    WARNINGS=$(_emit_warning "warn" "$WARN_ID" "$MSG" "$WARNINGS")
  fi
done

ENT_COUNT=$(jq 'length' <<< "$ENTITIES")
for k in $(seq 0 $((ENT_COUNT - 1))); do
  EN=$(jq -r ".[$k] | (.name // .id)" <<< "$ENTITIES")
  HAS_EP=$(jq --arg n "$EN" '[.[] | select(.entity == $n)] | length' <<< "$ENDPOINTS")
  if [[ "$HAS_EP" == "0" ]]; then
    WARN_ID="W-API-noep-${k}"
    MSG="Entity \`${EN}\` has no API endpoint — intentional?"
    WARNINGS=$(_emit_warning "warn" "$WARN_ID" "$MSG" "$WARNINGS")
  fi
done

rm -f "$USED_SCOPES_FILE"

CONTENT="${HEADER}${PATHS_STR}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
"

jq -n --arg content "$CONTENT" --argjson srcRefs "$SRC_REFS" --argjson warnings "$WARNINGS" \
  '{content: $content, sourceRefs: $srcRefs, crossCheckWarnings: $warnings}'
