#!/usr/bin/env bash
# render-db-drizzle.sh — R6 DB renderer (Drizzle ORM)
# Triggered when dataArchitecture.engine in {postgres,mysql,sqlite} AND language=drizzle.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=render-common.sh
source "${SCRIPT_DIR}/render-common.sh"

STATE_FILE="${1:?usage: render-db-drizzle.sh <state-file>}"
ENTITIES=$(_validate_jq_path "$STATE_FILE" '.phases.domainModel.entities // []' false)
PII=$(_validate_jq_path "$STATE_FILE" '.phases.privacy.piiFields // []' false)
ENGINE=$(_validate_jq_path "$STATE_FILE" '.phases.dataArchitecture.engine // "postgres"' false)

case "$ENGINE" in
  postgres|postgresql) DRIZZLE_PKG="drizzle-orm/pg-core"; INT_TYPE="integer"; TEXT_TYPE="text"; TIMESTAMP_TYPE="timestamp" ;;
  mysql)               DRIZZLE_PKG="drizzle-orm/mysql-core"; INT_TYPE="int"; TEXT_TYPE="varchar"; TIMESTAMP_TYPE="datetime" ;;
  sqlite)              DRIZZLE_PKG="drizzle-orm/sqlite-core"; INT_TYPE="integer"; TEXT_TYPE="text"; TIMESTAMP_TYPE="integer" ;;
  *)                   DRIZZLE_PKG="drizzle-orm/pg-core"; INT_TYPE="integer"; TEXT_TYPE="text"; TIMESTAMP_TYPE="timestamp" ;;
esac

HEADER="// Generated by greenfield render-db-drizzle.sh — review and edit freely after lock.
import { pgTable, integer, text, boolean, timestamp } from '${DRIZZLE_PKG}';
"

MODELS=""
SRC_REFS="[]"
WARNINGS="[]"

ENTITY_COUNT=$(jq 'length' <<< "$ENTITIES")
for i in $(seq 0 $((ENTITY_COUNT - 1))); do
  E=$(jq ".[$i]" <<< "$ENTITIES")
  NAME=$(jq -r '.name // .id // "Unknown"' <<< "$E")
  TABLE_NAME=$(echo "$NAME" | tr 'A-Z' 'a-z')

  ATTRS=$(jq '.attributes // []' <<< "$E")
  A_COUNT=$(jq 'length' <<< "$ATTRS")
  FIELDS_BLOCK="  id: ${INT_TYPE}('id').primaryKey(),"
  for j in $(seq 0 $((A_COUNT - 1))); do
    AN=$(jq -r ".[$j].name // \"f${j}\"" <<< "$ATTRS")
    AT=$(jq -r ".[$j].type // \"String\"" <<< "$ATTRS")
    case "$AT" in
      string|String|text)     DT="text('${AN}')" ;;
      int|integer|Int)        DT="integer('${AN}')" ;;
      bool|boolean|Boolean)   DT="boolean('${AN}')" ;;
      date|datetime|DateTime) DT="timestamp('${AN}')" ;;
      *)                      DT="text('${AN}')" ;;
    esac
    FIELDS_BLOCK="${FIELDS_BLOCK}
  ${AN}: ${DT},"
    WARNINGS=$(_check_pii_encryption "${NAME}.${AN}" "$PII" "$WARNINGS")
  done

  MODELS="${MODELS}
export const ${TABLE_NAME} = pgTable('${TABLE_NAME}', {
${FIELDS_BLOCK}
});
"
  SRC_REFS=$(jq --arg n "$NAME" '. + [{path: ("domainModel.entities[name=" + $n + "]"), renderedAs: ("Drizzle table " + $n)}]' <<< "$SRC_REFS")
done

CONTENT="${HEADER}${MODELS}"
jq -n --arg content "$CONTENT" --argjson srcRefs "$SRC_REFS" --argjson warnings "$WARNINGS" \
  '{content: $content, sourceRefs: $srcRefs, crossCheckWarnings: $warnings}'
