#!/usr/bin/env bash
# render-ci-circleci.sh — R6 CI renderer (CircleCI config.yml)

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=render-common.sh
source "${SCRIPT_DIR}/render-common.sh"

STATE_FILE="${1:?usage: render-ci-circleci.sh <state-file>}"
CI=$(_validate_jq_path "$STATE_FILE" '.phases.cicdAndDelivery // {}' true)
NODE_V=$(jq -r '.stack.nodeVersion // "20"' <<< "$CI")
STAGES=$(jq -r '.cicd.stages // ["lint","test","build"] | join(" ")' <<< "$CI")
DEPLOY_ENV=$(jq -r '.cicd.deploy.environment // ""' <<< "$CI")

WARNINGS="[]"

YAML="# Generated by greenfield render-ci-circleci.sh — review and edit freely after Approve.
version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build:
    docker:
      - image: cimg/node:${NODE_V}
    steps:
      - checkout
      - node/install-packages
"
for stage in $STAGES; do
  case "$stage" in
    lint)      cmd="npm run lint" ;;
    typecheck) cmd="npm run typecheck" ;;
    test)      cmd="npm test" ;;
    build)     cmd="npm run build" ;;
    *)         cmd="echo skip-${stage}" ;;
  esac
  YAML="${YAML}      - run:
          name: ${stage}
          command: ${cmd}
"
done

YAML="${YAML}
workflows:
  ci:
    jobs:
      - build
"

if [[ -n "$DEPLOY_ENV" && "$DEPLOY_ENV" != "null" ]]; then
  YAML="${YAML}      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main

  deploy:
    docker:
      - image: cimg/node:${NODE_V}
    environment:
      DEPLOY_ENV: ${DEPLOY_ENV}
    steps:
      - checkout
      - run: echo \"Deploy to \$DEPLOY_ENV — configure per project\"
"
fi

SRC_REFS=$(jq -n '[{"path":"cicdAndDelivery.cicd","renderedAs":"CircleCI workflow"}]')
jq -n --arg content "$YAML" --argjson srcRefs "$SRC_REFS" --argjson warnings "$WARNINGS" \
  '{content: $content, sourceRefs: $srcRefs, crossCheckWarnings: $warnings}'
