#!/usr/bin/env bash
# render-db-prisma.sh — R5 P10.5 DB renderer (Prisma)
#
# Reads domain model + privacy from $1 and emits a Prisma schema string
# wrapped in a JSON envelope to stdout. sourceRefs map each rendered model
# back to its origin entity. crossCheckWarnings surface aggregate-roots-without-PK
# and PII-without-encryption-hint.

set -euo pipefail
STATE_FILE="${1:?usage: render-db-prisma.sh <state-file>}"

ENTITIES=$(jq '.phases.domainModel.entities // []' "$STATE_FILE")
PII=$(jq '.phases.privacy.piiFields // []' "$STATE_FILE")

HEADER='// Generated by greenfield render-db-prisma.sh — review and edit freely after lock.
generator client {
  provider = "prisma-client-js"
}
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
'

MODELS=""
SRC_REFS="[]"
WARNINGS="[]"

ENTITY_COUNT=$(jq 'length' <<< "$ENTITIES")
for i in $(seq 0 $((ENTITY_COUNT - 1))); do
  E=$(jq ".[$i]" <<< "$ENTITIES")
  NAME=$(jq -r '.name // .id // "Unknown"' <<< "$E")
  IS_AGGREGATE_ROOT=$(jq -r '.isAggregateRoot // false' <<< "$E")
  PK_FIELD=$(jq -r '.primaryKey // ""' <<< "$E")

  if [[ "$IS_AGGREGATE_ROOT" == "true" && -z "$PK_FIELD" ]]; then
    WARN_ID="W-DB-${i}-pk"
    MSG="Aggregate root \`${NAME}\` has no PK field — cannot generate schema"
    WARNINGS=$(jq --arg id "$WARN_ID" --arg msg "$MSG" '. + [{id: $id, level: "error", message: $msg}]' <<< "$WARNINGS")
    PK_FIELD="id"
  fi
  [[ -z "$PK_FIELD" ]] && PK_FIELD="id"

  FIELDS_BLOCK="  ${PK_FIELD} String @id @default(cuid())"

  ATTRS=$(jq '.attributes // []' <<< "$E")
  A_COUNT=$(jq 'length' <<< "$ATTRS")
  for j in $(seq 0 $((A_COUNT - 1))); do
    AN=$(jq -r ".[$j].name // \"f${j}\"" <<< "$ATTRS")
    AT=$(jq -r ".[$j].type // \"String\"" <<< "$ATTRS")
    case "$AT" in
      string|String|text)     PT="String" ;;
      int|integer|Int)        PT="Int" ;;
      bool|boolean|Boolean)   PT="Boolean" ;;
      date|datetime|DateTime) PT="DateTime" ;;
      float|number|Float)     PT="Float" ;;
      *)                      PT="String" ;;
    esac
    [[ "$AN" == "$PK_FIELD" ]] && continue
    FIELDS_BLOCK="${FIELDS_BLOCK}
  ${AN} ${PT}"

    PII_HIT=$(jq --arg n "${NAME}.${AN}" '[.[] | select(.path == $n)] | length' <<< "$PII")
    if [[ "$PII_HIT" -gt 0 ]]; then
      HAS_ENCRYPTION=$(jq --arg n "${NAME}.${AN}" '[.[] | select(.path == $n) | .encryption // ""] | first // ""' <<< "$PII")
      if [[ -z "$HAS_ENCRYPTION" || "$HAS_ENCRYPTION" == "" ]]; then
        WARN_ID="W-DB-${i}-${j}-pii"
        MSG="Field \`${NAME}.${AN}\` (PII) has no encryption hint — review storage strategy"
        WARNINGS=$(jq --arg id "$WARN_ID" --arg msg "$MSG" '. + [{id: $id, level: "warn", message: $msg}]' <<< "$WARNINGS")
      fi
    fi
  done

  MODELS="${MODELS}
model ${NAME} {
${FIELDS_BLOCK}
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
"

  SRC_REFS=$(jq --arg p "phases.domainModel.entities[${i}]" --arg r "model ${NAME}" '. + [{path: $p, renderedAs: $r}]' <<< "$SRC_REFS")
done

CONTENT="${HEADER}${MODELS}"

jq -n --arg content "$CONTENT" --argjson srcRefs "$SRC_REFS" --argjson warnings "$WARNINGS" \
  '{content: $content, sourceRefs: $srcRefs, crossCheckWarnings: $warnings}'
