#!/usr/bin/env bash
# render-event-avro.sh — R6 Event renderer (Apache Avro)
# Triggered when apiIntegration.asyncPattern in {kafka,kinesis} AND language=avro.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=render-common.sh
source "${SCRIPT_DIR}/render-common.sh"

STATE_FILE="${1:?usage: render-event-avro.sh <state-file>}"
EVENTS=$(_validate_jq_path "$STATE_FILE" '.phases.domainModel.domainEvents // []' false)

SCHEMAS_ARRAY="["
SRC_REFS="[]"
WARNINGS="[]"

E_COUNT=$(jq 'length' <<< "$EVENTS")
for i in $(seq 0 $((E_COUNT - 1))); do
  EV=$(jq ".[$i]" <<< "$EVENTS")
  NAME=$(jq -r '.name // .id // ("Event" + ('"$i"'+1|tostring))' <<< "$EV")
  PAYLOAD=$(jq '.payload // []' <<< "$EV")

  FIELDS_JSON="["
  P_COUNT=$(jq 'length' <<< "$PAYLOAD")
  for j in $(seq 0 $((P_COUNT - 1))); do
    FN=$(jq -r ".[$j].name // \"f${j}\"" <<< "$PAYLOAD")
    FT=$(jq -r ".[$j].type // \"string\"" <<< "$PAYLOAD")
    case "$FT" in
      int|integer)    AT="int" ;;
      long)           AT="long" ;;
      bool|boolean)   AT="boolean" ;;
      float)          AT="float" ;;
      double|number)  AT="double" ;;
      bytes)          AT="bytes" ;;
      *)              AT="string" ;;
    esac
    [[ "$j" -gt 0 ]] && FIELDS_JSON="${FIELDS_JSON},"
    FIELDS_JSON="${FIELDS_JSON}{\"name\":\"${FN}\",\"type\":\"${AT}\"}"
  done
  FIELDS_JSON="${FIELDS_JSON}]"

  [[ "$i" -gt 0 ]] && SCHEMAS_ARRAY="${SCHEMAS_ARRAY},"
  SCHEMAS_ARRAY="${SCHEMAS_ARRAY}
  {\"type\":\"record\",\"name\":\"${NAME}\",\"namespace\":\"com.app.events\",\"fields\":${FIELDS_JSON}}"
  SRC_REFS=$(jq --arg n "$NAME" '. + [{path: ("domainModel.domainEvents[name=" + $n + "]"), renderedAs: ("Avro record " + $n)}]' <<< "$SRC_REFS")
done

SCHEMAS_ARRAY="${SCHEMAS_ARRAY}
]"

# Validate the assembled JSON is well-formed
echo "$SCHEMAS_ARRAY" | jq empty 2>/dev/null || WARNINGS=$(_emit_warning "error" "E-AVRO-JSON" "Assembled Avro schema array failed jq validation" "$WARNINGS")

CONTENT="// Generated by greenfield render-event-avro.sh — review and edit freely after lock.
${SCHEMAS_ARRAY}"

jq -n --arg content "$CONTENT" --argjson srcRefs "$SRC_REFS" --argjson warnings "$WARNINGS" \
  '{content: $content, sourceRefs: $srcRefs, crossCheckWarnings: $warnings}'
