#!/usr/bin/env bash
# render-ci-gitlab.sh — R6 CI renderer (GitLab CI YAML)

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=render-common.sh
source "${SCRIPT_DIR}/render-common.sh"

STATE_FILE="${1:?usage: render-ci-gitlab.sh <state-file>}"
CI=$(_validate_jq_path "$STATE_FILE" '.phases.cicdAndDelivery // {}' true)
NODE_V=$(jq -r '.stack.nodeVersion // "20"' <<< "$CI")
STAGES=$(jq -r '.cicd.stages // ["lint","test","build"] | join(" ")' <<< "$CI")
DEPLOY_ENV=$(jq -r '.cicd.deploy.environment // ""' <<< "$CI")

WARNINGS="[]"

YAML="# Generated by greenfield render-ci-gitlab.sh — review and edit freely after Approve.
image: node:${NODE_V}

stages:
"
for s in $STAGES; do YAML="${YAML}  - ${s}
"; done

cache="
cache:
  paths:
    - node_modules/
"

before="
before_script:
  - npm ci
"

YAML="${YAML}${cache}${before}"

for stage in $STAGES; do
  case "$stage" in
    lint)      cmd="npm run lint" ;;
    typecheck) cmd="npm run typecheck" ;;
    test)      cmd="npm test" ;;
    build)     cmd="npm run build" ;;
    *)         cmd="echo skip-${stage}" ;;
  esac
  YAML="${YAML}
${stage}:
  stage: ${stage}
  script:
    - ${cmd}
"
done

if [[ -n "$DEPLOY_ENV" && "$DEPLOY_ENV" != "null" ]]; then
  YAML="${YAML}
deploy:
  stage: deploy
  only:
    - main
  script:
    - echo \"Deploy to ${DEPLOY_ENV} — configure per project\"
  environment:
    name: ${DEPLOY_ENV}
"
fi

SRC_REFS=$(jq -n '[{"path":"cicdAndDelivery.cicd","renderedAs":"GitLab CI workflow"}]')
jq -n --arg content "$YAML" --argjson srcRefs "$SRC_REFS" --argjson warnings "$WARNINGS" \
  '{content: $content, sourceRefs: $srcRefs, crossCheckWarnings: $warnings}'
