#!/usr/bin/env bash
# render-ci-gha.sh — R6 CI renderer (GitHub Actions YAML)
# Reads phases.cicdAndDelivery and emits .github/workflows/ci.yml content.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=render-common.sh
source "${SCRIPT_DIR}/render-common.sh"

STATE_FILE="${1:?usage: render-ci-gha.sh <state-file>}"
CI=$(_validate_jq_path "$STATE_FILE" '.phases.cicdAndDelivery // {}' true)
# shellcheck disable=SC2034  # FRAMEWORK reserved for framework-specific CI steps (future tasks)
FRAMEWORK=$(_validate_jq_path "$STATE_FILE" '.phases.architecturalFraming.frontendFramework // ""' false)
HAS_TS=$(_validate_jq_path "$STATE_FILE" '.phases.stack.language // "" | contains("typescript") | tostring' false)

STAGES=$(jq -r '.cicd.stages // ["lint","test","build"] | join(",")' <<< "$CI")
RUNNERS=$(jq -r '.cicd.runners // "ubuntu-latest"' <<< "$CI")
NODE_V=$(jq -r '.stack.nodeVersion // "20"' <<< "$CI")
DEPLOY_ENV=$(jq -r '.cicd.deploy.environment // ""' <<< "$CI")

WARNINGS="[]"

# Cross-checks
if [[ "$HAS_TS" != "true" ]] && jq -e '.cicd.stages // [] | index("typecheck")' <<< "$CI" >/dev/null 2>&1; then
  WARNINGS=$(_emit_warning "warn" "W-CI-GHA-typecheck" "Stage 'typecheck' enabled but stack.language does not include typescript" "$WARNINGS")
fi

YAML="# Generated by greenfield render-ci-gha.sh — review and edit freely after Approve.
name: CI

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  build:
    runs-on: ${RUNNERS}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '${NODE_V}'
          cache: 'npm'
      - run: npm ci
"

IFS=',' read -ra STAGE_LIST <<< "$STAGES"
for stage in "${STAGE_LIST[@]}"; do
  case "$stage" in
    lint)      YAML="${YAML}      - run: npm run lint
" ;;
    typecheck) YAML="${YAML}      - run: npm run typecheck
" ;;
    test)      YAML="${YAML}      - run: npm test
" ;;
    build)     YAML="${YAML}      - run: npm run build
" ;;
  esac
done

if [[ -n "$DEPLOY_ENV" && "$DEPLOY_ENV" != "null" ]]; then
  YAML="${YAML}
  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ${RUNNERS}
    environment: ${DEPLOY_ENV}
    steps:
      - uses: actions/checkout@v4
      - run: echo \"Deploy step — configure per project (Vercel, AWS, etc.)\"
"
fi

SRC_REFS=$(jq -n '[{"path":"cicdAndDelivery.cicd","renderedAs":"GHA workflow"}]')
jq -n --arg content "$YAML" --argjson srcRefs "$SRC_REFS" --argjson warnings "$WARNINGS" \
  '{content: $content, sourceRefs: $srcRefs, crossCheckWarnings: $warnings}'
