#!/usr/bin/env bash
# render-api-hasura.sh — R6 API renderer (Hasura metadata + permissions YAML)
# Triggered when apiIntegration.style = hasura.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=render-common.sh
source "${SCRIPT_DIR}/render-common.sh"

STATE_FILE="${1:?usage: render-api-hasura.sh <state-file>}"
ENTITIES=$(_validate_jq_path "$STATE_FILE" '.phases.domainModel.entities // []' false)
ROLES=$(_validate_jq_path "$STATE_FILE" '.phases.auth.roles // ["public","authenticated"]' false)

YAML="# Generated by greenfield render-api-hasura.sh — review and edit freely after lock.
version: 3
tables:
"
SRC_REFS="[]"
WARNINGS="[]"

E_COUNT=$(jq 'length' <<< "$ENTITIES")
for i in $(seq 0 $((E_COUNT - 1))); do
  E=$(jq ".[$i]" <<< "$ENTITIES")
  NAME=$(jq -r '.name // .id // "Unknown"' <<< "$E")
  TABLE_NAME=$(echo "$NAME" | tr 'A-Z' 'a-z')

  YAML="${YAML}  - table:
      schema: public
      name: ${TABLE_NAME}
    select_permissions:
"
  R_COUNT=$(jq 'length' <<< "$ROLES")
  for j in $(seq 0 $((R_COUNT - 1))); do
    ROLE=$(jq -r ".[$j]" <<< "$ROLES")
    YAML="${YAML}      - role: ${ROLE}
        permission:
          columns: '*'
          filter: {}
"
  done
  SRC_REFS=$(jq --arg n "$NAME" '. + [{path: ("domainModel.entities[name=" + $n + "]"), renderedAs: ("Hasura table " + $n)}]' <<< "$SRC_REFS")
done

jq -n --arg content "$YAML" --argjson srcRefs "$SRC_REFS" --argjson warnings "$WARNINGS" \
  '{content: $content, sourceRefs: $srcRefs, crossCheckWarnings: $warnings}'
